name: Daily Commit 

on: 
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch: 

  permissions:
    contents: write

  jobs:
    commit:
      runs-on: ubuntu-latest
      steps:
        - name: Checkout Repository
          uses: actions/checkout@v4

        - name: Configure Git (22f1001202@ds.study.iitm.ac.in)
          run: |
            git config --global user.name "Github Action"
            git config --global user.email "22f1001202@ds.study.iitm.ac.in"

        - name: Make a change
          run: |
            echo: "Last run: $(date)" > last_run.txt

        - name: Commit and push changes 
          run: |
            git add last_run.txt
            git commit -m "Automated daily commit at $(date)" || echo "No changes to commit"
            git push
  
